#!/bin/bash
# Quick PostgreSQL Setup Reference

echo "PostgreSQL Connection Reference"
echo "========================================"
echo ""
echo "✓ PostgreSQL is running"
echo "✓ Database 'job_intelligence' exists"
echo "✓ User 'user' created"
echo ""
echo "QUICK START:"
echo "--------"
echo ""
echo "1. Test connection:"
echo "   psql -h localhost -U user -d job_intelligence"
echo ""
echo "2. Update .env file:"
echo "   DATABASE_URL=postgresql://user:YOUR_PASSWORD@localhost:5432/job_intelligence"
echo ""
echo "3. Install dependencies:"
echo "   cd backend && pip install -r requirements.txt"
echo ""
echo "4. Run backend:"
echo "   cd backend && python -m uvicorn app.main:app --reload"
echo ""
echo "TROUBLESHOOTING:"
echo "--------"
echo ""
echo "Connection fails?"
echo "  • Check if password is correct in .env"
echo "  • Verify PostgreSQL is running: sudo systemctl status postgresql"
echo "  • Always use -h localhost for TCP connection"
echo ""
echo "Database issues?"
echo "  • Check tables: psql -h localhost -U user -d job_intelligence -c '\\dt'"
echo "  • Reset password: sudo -u postgres psql -c \"ALTER USER \\\"user\\\" WITH PASSWORD 'newpass';\""
echo ""
echo "========================================"
